language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: pages:git
  edge: true
  token: $github_token
  local_dir: dist
  on:
    branch: src
