branches:
  except:
  - master
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn run build
- ls -l dist
deploy:
  provider: pages:git
  edge: true
  target_branch: master
  token:
    secure: I0eUK7rmTHDl3R/mFtBbuJi1n7lUEYLjbdXBglKqQpJv+EWusF7MoPQph1ygm5l/KRHkpLGH4Q5ZGZbElWSLYsvBAj+lEQk3ujcWYkB47cMY7ZKj/03vbW5bt06U7cn1DlbNxXSQDRhTV0rzZU4vuBcTl9b4qeowuwYZWDDiEF0yOdPymmk343VDuiiL+l5lZCQBxuZahl/nSS1C3pnlshY1CeKd5+VFlC9S5HOorrEUVmUz0wqDSiQAEPfKiBSvYCAHcnGp0sixQ370DbzaM6FE/hVz8hjz4ATP147BrbGX4UlKyyxOkit40uxGkhLCMnz38dl7QV0h74kj0wHKpXxd632BIEYxtPR+jj0/G05o2ngGanr5pRgttohzbWtWLlkwo860U0vidzx0AchyN2Y20KnOuVCAlA9qh3DD9gQf79suhEl7ZCS/Srd7UMO/QUmWrpRbax5x/DKIa9LtlGi/mvSNAXsuTxo1xxo8sogEfZ/M0iJkJsXlC66lJiMNVLVJt7B6MThG51FSmXJzMFeHbPFDoE3ukKnBLLGtjdR3JqkmPaDoAXEAEYLKKmVZvDzCjYiphT9Tb9MhbOUDK8NxZKquU3/OZiwigotfdnOJ28ogUAsrpfOd2xH3pxVQqzj8H58Js0mvKRyibKJimEX/ghHuCompsUYUS67FMUQ=
  local_dir: dist
  on:
    branch: src
