name: Build and Deploy site

on:
  push:
    branches:
    - src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Write config file
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "src/config.js"
        FILE_DATA: "export default { HOST: 'https://elastic.thingy-ma-jig.co.uk/', ELASTIC_INDEX: 'prod_drupal' }"
    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: master
        folder: 'dist'
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        clean: true
