name: Build and Deploy site

on:
  push:
    branches:
    - src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Write config file
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "src/config.js"
        FILE_DATA: "export default { ELASTIC_INDEX: 'prod_drupal' }"
    - name: Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: master
        FOLDER: 'dist'
        CLEAN: true
