name: Build and Deploy site

on:
  push:
    branches:
    - src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env: {
        FILE_NAME: "src/config.js"
        FILE_DATA: "export default { ELASTIC_INDEX: 'prod_drupal' }"
      }
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: 'dist'
        CLEAN: true
